server:
  port: 8763
spring:
  data:
    mongodb:
      database: preference-center
      port: 27017
      host: ${MONGO_DB:localhost}

springdoc:
  packagesToScan: com.tgtech.preferencecenter.controller