apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eureka
  template:
    metadata:
      labels:
        component: eureka
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER
              value: http://config-server-cluster-ip-service:8762
            - name: EUREKA_SERVER
              value: http://eureka-cluster-ip-service:8761/eureka
          image: samiraghayarov/discovery-service
          name: eureka
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: eureka
  ports:
    - port: 8761
      targetPort: 8761
